/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    AButton: (typeof import("@arco-design/web-vue"))["Button"];
    ACard: (typeof import("@arco-design/web-vue"))["Card"];
    ADivider: (typeof import("@arco-design/web-vue"))["Divider"];
    AForm: (typeof import("@arco-design/web-vue"))["Form"];
    AFormItem: (typeof import("@arco-design/web-vue"))["FormItem"];
    AInput: (typeof import("@arco-design/web-vue"))["Input"];
    ASelect: (typeof import("@arco-design/web-vue"))["Select"];
    ASpace: (typeof import("@arco-design/web-vue"))["Space"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
  }
}
